#!/bin/bash

# Download some files from github.com and verify them with sha512sum.


qb_tag=b8c9897173b2daa6c0566dcf74a6f32adf445074
qb_url=https://raw.githubusercontent.com/lanceman2/quickbuild/$qb_tag/quickbuild.make

qb_sha512sum=37fecdb53c5cb8d0ebdadf80cc77df65af0\
36e56ea1cc76ae0af4d7857f25a3d557a1685938b7dc12de\
46964d140b203fd4fcae749ecf03ac93a361fa6769762


set -ex

# Go to the directory there this script is.
cd $(dirname ${BASH_SOURCE[0]})



# GetFile DIR FILENAME URL [SHA512SUM]
# $0      $1  $2       $3  $4
function GetFile() {

    [ -n "$3" ] || exit 1

    cd $1

    if [ ! -e "$2" ] ; then
        wget --no-check-certificate "$3" -O "$2"
    fi

    if [ -n "$4" ] ; then
        set +x
        # We wanted a particular file, so we check its' sha512 sum.
        echo "$4  $2" | sha512sum -c
        set -x
    else
        sha512sum "$2"
    fi

    cd -
}

# GetFile DIR FILENAME URL [SHA512SUM]

GetFile . quickbuild.make $qb_url $qb_sha512sum


set +x
echo -e "\n$0 Success"
