#!/bin/bash

# Download some files from github.com and verify them with sha512sum.


qb_tag=0.4
qb_url=https://raw.githubusercontent.com/lanceman2/quickbuild/$qb_tag/quickbuild.make
qb_sha512sum=df58b143ab84d7f30dfae36c869226f6a6d3\
299dd14193e4623cf23381ae5cf14aca7781adfee6a5ac9cc\
99b1cc751cdd2974cda426647718ab9f669c35d652e

debug_tag=52cd14fab044ea217e2dd3b4ebdc2faf63cd4fcb
debug_url=https://raw.githubusercontent.com/lanceman2/debug/$debug_tag/
debug_c_sha512sum=6b85e9448641b2e2f34caef4a4323b3\
57cb0c43fd3401c0955a9a29dd5210de0a0e08638dc5ddd4f\
69bf67e871c132e38d24cd19aa608450a2b7dfe676df90b1
debug_h_sha512sum=3ea899b49cd23959a6d265a05d9bdbc\
1dc9d6a29822413ada99aa47df7bf746ff856f5fb6fc9c893\
348370451fb27e14913340cd831828afdfe889edcdaefcaf


set -ex

# Go to the directory there this script is.
cd $(dirname ${BASH_SOURCE[0]})



# GetFile DIR FILENAME URL [SHA512SUM]
# $0      $1  $2       $3  $4
function GetFile() {

    [ -n "$3" ] || exit 1

    cd $1

    if [ ! -e "$2" ] ; then
        wget --no-check-certificate "$3" -O "$2"
    fi

    if [ -n "$4" ] ; then
        set +x
        # We wanted a particular file, so we check its' sha512 sum.
        echo "$4  $2" | sha512sum -c
        set -x
    else
        sha512sum "$2"
    fi

    cd -
}

# GetFile DIR FILENAME URL [SHA512SUM]

GetFile . quickbuild.make $qb_url $qb_sha512sum
GetFile lib debug.c $debug_url/debug.c $debug_c_sha512sum
GetFile lib debug.h $debug_url/debug.h $debug_h_sha512sum


set +x
echo -e "\n$0 Success"
